//! Vault accept-invite wire types (hub-blind redesign).
//!
//! - [`InviteOuterSummary`] — the only part the hub stores. Carries
//!   `cluster_id`, `invite_nonce`, `expires_at_ms`,
//!   `inner_payload_hash`, and the outer admin signature. Hub
//!   verifies signature against the cluster admin pubkey to gate
//!   admission.
//! - [`InviteInnerPayload`] — out-of-band only. Transmitted from
//!   admin to vault operator (typically embedded in the invite
//!   string the operator pastes). Carries `vault_role`, `hub_url`,
//!   `hub_cert_fingerprint`, the per-invite `invite_kek_secret`
//!   (used together with the outer's `invite_nonce` to derive the
//!   KEK), and the AEAD-sealed `cluster_shared_key`. See
//!   `crate::crypto::invite_kek`.

use serde::{Deserialize, Serialize};

use crate::crypto::invite_kek::InviteKekSecret;
use crate::crypto::pq::{MlDsa65PublicKey, MlDsa65Signature};
use crate::types::{ClusterId, FormatVersion, VaultId};

/// Roles a vault can hold within a cluster.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum VaultRole {
    /// Storage vault (default — holds chunks, runs replication).
    Storage,
}

/// What the hub stores for a registered invite.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InviteOuterSummary {
    pub format_version: FormatVersion,
    pub cluster_id: ClusterId,
    #[serde(with = "serde_bytes")]
    pub invite_nonce: Vec<u8>,
    pub expires_at_ms: u64,
    /// SHA-256 of CBOR-encoded [`InviteInnerPayload`]. Hub verifies
    /// the vault's submitted inner payload matches this hash.
    #[serde(with = "serde_bytes")]
    pub inner_payload_hash: Vec<u8>,
    pub sig_admin_outer: MlDsa65Signature,
}

/// Out-of-band only. Carries everything the hub MUST NOT see.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct InviteInnerPayload {
    pub format_version: FormatVersion,
    pub vault_role: VaultRole,
    pub hub_url: String,
    /// `sha256:<base64url-no-padding>` SPKI hash of the hub TLS leaf cert.
    pub hub_cert_fingerprint: String,
    /// 32 random bytes generated by the admin per invite. Combined
    /// with the outer's `invite_nonce` to derive the KEK that opens
    /// `sealed_cluster_key`. Confidential — must travel only through
    /// the operator's confidential channel (in mini-MVP, alongside
    /// the rest of this struct in one base64url-CBOR token).
    pub invite_kek_secret: InviteKekSecret,
    /// `nonce(24) || aead_ct(cluster_shared_key:32 + tag:16)` sealed
    /// under [`crate::crypto::invite_kek::InviteKek`] with AAD =
    /// [`crate::crypto::invite_kek::SEALED_CLUSTER_KEY_AAD`].
    #[serde(with = "serde_bytes")]
    pub sealed_cluster_key: Vec<u8>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInviteRequest {
    pub invite: InviteOuterSummary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateInviteResponse {
    pub invite: InviteOuterSummary,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AcceptRequest {
    pub invite_outer: InviteOuterSummary,
    pub invite_inner: InviteInnerPayload,
    pub vault_pubkey: MlDsa65PublicKey,
    /// Vault's signature over `invite_nonce || vault_pubkey_bytes`,
    /// proving possession of the secret half of `vault_pubkey`.
    pub sig_vault: MlDsa65Signature,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AcceptResponse {
    pub cluster_id: ClusterId,
    pub vault_id: VaultId,
    pub cluster_admin_pubkey: MlDsa65PublicKey,
    /// Outer envelope of the latest admin chain entry the hub knows
    /// about. The vault verifies its signature against
    /// `cluster_admin_pubkey` and unseals locally.
    pub chain_head: crate::crypto::admin_chain::AdminChainEntry,
}

/// Stable byte layout the cluster admin signs when producing
/// `InviteOuterSummary::sig_admin_outer`. Identical bytes must be
/// reproduced anywhere the signature is verified (admin CLI on
/// invite issue, hub on `create_invite` / `accept` / `bootstrap`,
/// vault on local invite-sanity check).
#[must_use]
pub fn invite_outer_signed_bytes(outer: &InviteOuterSummary) -> Vec<u8> {
    let mut out = Vec::with_capacity(
        1 + outer.cluster_id.as_bytes().len() + outer.invite_nonce.len() + 8 + 32,
    );
    out.push(outer.format_version.as_u8());
    out.extend_from_slice(outer.cluster_id.as_bytes());
    out.extend_from_slice(&outer.invite_nonce);
    out.extend_from_slice(&outer.expires_at_ms.to_be_bytes());
    out.extend_from_slice(&outer.inner_payload_hash);
    out
}
