//! Per-invite key-encrypting-key (KEK) used to seal `cluster_shared_key`
//! inside the invite token's inner payload (K2 delivery).
//!
//! Both admin and vault must be able to derive the same KEK from
//! material each one holds. We use a per-invite symmetric secret
//! (`InviteKekSecret`) generated by the admin and transported inside
//! the (confidential, out-of-band) inner payload alongside
//! `sealed_cluster_key`. Symmetric inputs:
//!
//! ```text
//! invite_kek = HKDF-SHA-256(
//!     ikm  = invite_kek_secret,
//!     salt = invite_nonce,
//!     info = "vitonomi/invite_kek/v1",
//!     out_len = 32,
//! )
//! ```
//!
//! Threat-model commentary: in the mini-MVP the inner payload is one
//! base64url-CBOR blob the operator transmits as a single string, so
//! `invite_kek_secret` and `sealed_cluster_key` travel together —
//! anyone with the invite can unseal. The seal then provides
//! AAD-bound integrity + future architectural readiness: in v1.1+
//! the admin can transmit the two halves over separate confidential
//! channels (e.g. QR + Signal), at which point a leak of either
//! alone reveals nothing.

use hkdf::Hkdf;
use sha2::Sha256;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::crypto::aead::AeadKey;
use crate::errors::CryptoError;

/// HKDF info string for invite-KEK derivation.
pub const INFO: &[u8] = b"vitonomi/invite_kek/v1";

/// AAD passed to AEAD seal/open on `sealed_cluster_key`. Anchors the
/// ciphertext to its purpose — flipping the AAD invalidates the seal.
pub const SEALED_CLUSTER_KEY_AAD: &[u8] = b"vitonomi/invite_kek/v1";

/// Length in bytes of [`InviteKekSecret`] and the derived [`InviteKek`].
pub const KEK_SECRET_LEN: usize = 32;

/// 32-byte per-invite secret. Generated freshly by the admin per
/// invite and shipped inside the (out-of-band) inner payload. Both
/// admin and vault feed this into HKDF together with `invite_nonce`
/// to derive the same [`InviteKek`].
///
/// `PartialEq`/`Eq` are NOT constant-time; they're provided only so
/// containers like the wire-level `InviteInnerPayload` can derive
/// equality for tests. Never use direct equality to gate authn —
/// the only consumer of this type's bytes is HKDF, which is the
/// correct path for converting the secret into key material.
#[derive(
    Debug, Clone, PartialEq, Eq, Zeroize, ZeroizeOnDrop, serde::Serialize, serde::Deserialize,
)]
pub struct InviteKekSecret(#[serde(with = "serde_bytes")] pub Vec<u8>);

impl InviteKekSecret {
    /// Generate a fresh 32-byte secret using the central RNG.
    ///
    /// # Errors
    ///
    /// `CryptoError::Random` on RNG failure.
    pub fn generate() -> Result<Self, CryptoError> {
        Ok(Self(crate::crypto::random::random_bytes(KEK_SECRET_LEN)?))
    }

    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        &self.0
    }
}

/// 32-byte invite-scoped KEK. Zeroised on drop.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct InviteKek(pub Vec<u8>);

impl InviteKek {
    /// Derive the KEK from the per-invite secret and the
    /// `invite_nonce` (which is in the hub-readable outer summary).
    ///
    /// # Errors
    ///
    /// `CryptoError::KeyLength` if the secret is not 32 bytes.
    pub fn derive(secret: &InviteKekSecret, invite_nonce: &[u8]) -> Result<Self, CryptoError> {
        if secret.0.len() != KEK_SECRET_LEN {
            return Err(CryptoError::KeyLength {
                expected: KEK_SECRET_LEN,
                got: secret.0.len(),
            });
        }
        let hk = Hkdf::<Sha256>::new(Some(invite_nonce), &secret.0);
        let mut out = [0u8; 32];
        hk.expand(INFO, &mut out)
            .expect("HKDF expand for invite_kek cannot fail at out_len=32");
        Ok(Self(out.to_vec()))
    }

    /// Wrap as an [`AeadKey`] for sealing/unsealing the inner payload.
    #[must_use]
    pub fn to_aead_key(&self) -> AeadKey {
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&self.0);
        AeadKey::from_bytes(arr)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crypto::aead::{open, seal};
    use crate::crypto::cluster_keys::ClusterSharedKey;

    fn fixed_secret(byte: u8) -> InviteKekSecret {
        InviteKekSecret(vec![byte; KEK_SECRET_LEN])
    }

    #[test]
    fn deterministic_for_same_inputs() {
        let s = fixed_secret(0x11);
        let nonce = vec![0xaa; 32];
        let k1 = InviteKek::derive(&s, &nonce).unwrap();
        let k2 = InviteKek::derive(&s, &nonce).unwrap();
        assert_eq!(k1.0, k2.0);
    }

    #[test]
    fn different_nonces_diverge() {
        let s = fixed_secret(0x22);
        assert_ne!(
            InviteKek::derive(&s, &vec![1u8; 32]).unwrap().0,
            InviteKek::derive(&s, &vec![2u8; 32]).unwrap().0,
        );
    }

    #[test]
    fn different_secrets_diverge() {
        let nonce = vec![0u8; 32];
        assert_ne!(
            InviteKek::derive(&fixed_secret(0x01), &nonce).unwrap().0,
            InviteKek::derive(&fixed_secret(0x02), &nonce).unwrap().0,
        );
    }

    #[test]
    fn wrong_secret_length_rejected() {
        let nonce = vec![0u8; 32];
        let s = InviteKekSecret(vec![0u8; 16]);
        match InviteKek::derive(&s, &nonce) {
            Err(CryptoError::KeyLength { expected, got }) => {
                assert_eq!(expected, KEK_SECRET_LEN);
                assert_eq!(got, 16);
            }
            Err(other) => panic!("expected KeyLength error, got {other}"),
            Ok(_) => panic!("expected KeyLength error, got Ok"),
        }
    }

    #[test]
    fn admin_and_vault_derive_the_same_kek() {
        let admin_secret = InviteKekSecret::generate().unwrap();
        let nonce = crate::crypto::random::random_bytes(32).unwrap();
        let admin_kek = InviteKek::derive(&admin_secret, &nonce).unwrap();
        // Vault simulates the same derivation given the secret it
        // receives in the inner payload + nonce from the outer.
        let vault_kek = InviteKek::derive(&admin_secret, &nonce).unwrap();
        assert_eq!(admin_kek.0, vault_kek.0);
    }

    #[test]
    fn round_trip_seal_then_open_matches_original() {
        let secret = InviteKekSecret::generate().unwrap();
        let nonce = crate::crypto::random::random_bytes(32).unwrap();
        let csk = ClusterSharedKey(crate::crypto::random::random_bytes(32).unwrap());
        let kek = InviteKek::derive(&secret, &nonce).unwrap();

        let sealed = seal(&kek.to_aead_key(), csk.as_bytes(), SEALED_CLUSTER_KEY_AAD).unwrap();
        let opened = open(&kek.to_aead_key(), &sealed, SEALED_CLUSTER_KEY_AAD).unwrap();
        assert_eq!(opened, csk.as_bytes());
    }

    #[test]
    fn tampered_seal_fails_open() {
        let secret = InviteKekSecret::generate().unwrap();
        let nonce = crate::crypto::random::random_bytes(32).unwrap();
        let csk = ClusterSharedKey(crate::crypto::random::random_bytes(32).unwrap());
        let kek = InviteKek::derive(&secret, &nonce).unwrap();
        let mut sealed = seal(&kek.to_aead_key(), csk.as_bytes(), SEALED_CLUSTER_KEY_AAD).unwrap();
        // Flip one byte in the ciphertext / tag region.
        let last = sealed.len() - 1;
        sealed[last] ^= 0x01;
        assert!(open(&kek.to_aead_key(), &sealed, SEALED_CLUSTER_KEY_AAD).is_err());
    }

    #[test]
    fn wrong_nonce_fails_open() {
        let secret = InviteKekSecret::generate().unwrap();
        let nonce = vec![0xaa; 32];
        let other_nonce = vec![0xbb; 32];
        let csk = ClusterSharedKey(crate::crypto::random::random_bytes(32).unwrap());
        let kek_a = InviteKek::derive(&secret, &nonce).unwrap();
        let kek_b = InviteKek::derive(&secret, &other_nonce).unwrap();
        let sealed = seal(&kek_a.to_aead_key(), csk.as_bytes(), SEALED_CLUSTER_KEY_AAD).unwrap();
        assert!(open(&kek_b.to_aead_key(), &sealed, SEALED_CLUSTER_KEY_AAD).is_err());
    }
}
